# This is a basic workflow to help you get started with Actions

name: MPI CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events in every branch
  # pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "mambaforge-mpi-hy"
  mambaforge-mpi-hy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@HEAD

      - name: Cache conda
        uses: actions/cache@HEAD
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('singular-poisson/conda-linux-64.lock') }}

      - name: Mambaforge lock
        uses: conda-incubator/setup-miniconda@HEAD
        with:
          environment-file: singular-poisson/conda-linux-64.lock
          miniforge-variant: Mambaforge
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      # Runs a set of commands using the runners shell
      - name: mpirun hy
        run: |
          mpirun -profile hy -B singular-poisson/run_demo.hy

      - uses: actions/upload-artifact@HEAD
        with:
          name: out-csv
          path: out.csv
